version: '3'

services:
  web:
    image: nginx
    ports:
      - 80:80
    volumes:
      - /etc/nginx/:/etc/nginx/
  spring:
    image: hyunseojeong/spring-gift:latest
    ports:
      - 8080:8080
    volumes:
      - ./:/root/